spring.application.name=ms-mascotas
server.port=8081

#registro en Eureka (descubrimiento de servicios)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
#conexion a la base de datos sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:mascotas.db

#apaga,ps a spring.jpa.hibernate.ddl-auto para que no intente crear o modificar la base de datos, ya que Flyway se encargará de eso
spring.jpa.hibernate.ddl-auto=none

#activo Flyway para que ejecute las migraciones al iniciar la aplicacion
spring.flyway.enabled=true

#muestra las consultas SQL en la consola para depuracion
spring.jpa.show-sql=true 